
#define AC_BASE                          (0x7AUL)
#define AC_CTRL_STATUS_BASE              (0x50UL)
#define AC_DIGITAL_INPUT_BASE            (0x7FUL)

#define AC_MULTIPLEXER_ENABLE            (1 << 6) 

#define AC_DISABLE                       (1 << 7)
#define AC_BANDGAP_SELECT                (1 << 6)
#define AC_OUTPUT                        (1 << 5)
#define AC_INTERRUPT_FLAG                (1 << 4)
#define AC_INTERRUPT_ENABLE              (1 << 3)
#define AC_INPUT_CAPTURE_ENABLE          (1 << 2)
#define AC_INTERRUPT_FALLING_OUTPUT_EDGE (1 << 1)
#define AC_INTERRUPT_RISING_OUTPUT_EDGE  (1 << 0) | (1 << 1)

#define AC_AIN0_DISABLE                  (1 << 0)
#define AC_AIN1_DISABLE                  (1 << 1)

#define AC_NEGATIVE_INPUT_AIN1           -1
#define AC_NEGATIVE_INPUT_ADC0           (0x00)  
#define AC_NEGATIVE_INPUT_ADC1           (0x01)
#define AC_NEGATIVE_INPUT_ADC2           (0x02)
#define AC_NEGATIVE_INPUT_ADC3           (0x03)
#define AC_NEGATIVE_INPUT_ADC4           (0x04)
#define AC_NEGATIVE_INPUT_ADC5           (0x05)
#define AC_NEGATIVE_INPUT_ADC6           (0x06)
#define AC_NEGATIVE_INPUT_ADC7           (0x07)
#define AC_NEGATIVE_INPUT_ADC8           (0x08)
#define AC_NEGATIVE_INPUT_ADC9           (0x09)
#define AC_NEGATIVE_INPUT_ADC10          (0x0A)
#define AC_NEGATIVE_INPUT_ADC11          (0x0B)
#define AC_NEGATIVE_INPUT_ADC12          (0x0C)
#define AC_NEGATIVE_INPUT_ADC13          (0x0D)
#define AC_NEGATIVE_INPUT_ADC14          (0x0E)
#define AC_NEGATIVE_INPUT_ADC15          (0x0F)