#define MCU_STATUS_BASE (0x55UL)
#define WATCHDOG_CTRL_BASE   (0x60UL)

#define JTAG_RESET_FLAG              (1 << 4)
#define WATCHDOG_RESET_FLAG          (1 << 3)
#define BROWN_OUT_RESET_FLAG         (1 << 2)
#define EXTERNAL_RESET_FLAG          (1 << 1)
#define POWER_ON_RESET_FLAG          (1 << 0)

#define WATCHDOG_INTERRUPT_FLAG      (1 << 7)
#define WATCHDOG_INTERRUPT_ENABLE    (1 << 6)
#define WATCHDOG_CHANGE_ENABLE       (1 << 4)
#define WATCHDOG_SYSTEM_RESET_ENABLE (1 << 3)
#define WATCHDOG_PRESCALER_4K        (1 << 0)
#define WATCHDOG_PRESCALER_8K        (1 << 1)
#define WATCHDOG_PRESCALER_16K       (1 << 0) | (1 << 1)
#define WATCHDOG_PRESCALER_32K       (1 << 2)
#define WATCHDOG_PRESCALER_64K       (1 << 0) | (1 << 2)
#define WATCHDOG_PRESCALER_128K      (1 << 1) | (1 << 2)
#define WATCHDOG_PRESCALER_256K      (1 << 0) | (1 << 1) | (1 << 2)
#define WATCHDOG_PRESCALER_512K      (1 << 5)
#define WATCHDOG_PRESCALER_1024K     (1 << 0) | (1 << 5)