
#define TIMER1_BASE                                     (0x80UL)
#define TIMER3_BASE                                     (0x90UL)
#define TIMER4_BASE                                     (0xA0UL)
#define TIMER5_BASE                                     (0x120UL)

#define TIMER1_ISR_BASE                                 (0x6FUL)
#define TIMER3_ISR_BASE                                 (0x71UL)
#define TIMER4_ISR_BASE                                 (0x72UL)
#define TIMER5_ISR_BASE                                 (0x73UL)

#define TIMER1_ISR_FLAGS_BASE                           (0x36UL)
#define TIMER3_ISR_FLAGS_BASE                           (0x38UL)
#define TIMER4_ISR_FLAGS_BASE                           (0x39UL)
#define TIMER5_ISR_FLAGS_BASE                           (0x3AUL)

#define TIMER_SYNC_CTRL_BASE                            (0x43UL)

#define TIMER16BIT_PWM_PHASE_CORRECT_8BIT                    (0x01)
#define TIMER16BIT_PWM_PHASE_CORRECT_9BIT                    (0x02)
#define TIMER16BIT_PWM_PHASE_CORRECT_10BIT                   (0x03)
#define TIMER16BIT_CTC_OCRnA_TOP                             (0x08)
#define TIMER16BIT_FAST_PWM_8BIT                             (0x09)
#define TIMER16BIT_FAST_PWM_9BIT                             (0x0A)
#define TIMER16BIT_FAST_PWM_10BIT                            (0x0B)
#define TIMER16BIT_PWM_PHASEFREQ_CORRECT_ICRn_TOP            (0x10)
#define TIMER16BIT_PWM_PHASEFREQ_CORRECT_OCRnA_TOP           (0x11)
#define TIMER16BIT_PWM_PHASE_CORRECT_ICRn_TOP                (0x12)
#define TIMER16BIT_PWM_PHASE_CORRECT_OCRnA_TOP               (0x13)
#define TIMER16BIT_CTC_ICRn_TOP                              (0x18)
#define TIMER16BIT_FAST_PWM_ICRn_TOP                         (0x1A)
#define TIMER16BIT_FAST_PWM_OCRnA_TOP                        (0x1B)

#define TIMER16BIT_INPUT_CAPTURE_EDGE_SELECT                 (1 << 6)
#define TIMER16BIT_INPUT_CAPTURE_NOISE_CANCELER              (1 << 7)

#define TIMER16BIT_NO_PRESCALER                              (1 << 0)
#define TIMER16BIT_8PRESCALER                                (1 << 1)
#define TIMER16BIT_64PRESCALER                               (1 << 0) | (1 << 1)
#define TIMER16BIT_256PRESCALER                              (1 << 2)
#define TIMER16BIT_1024PRESCALER                             (1 << 0) | (1 << 2)
#define TIMER16BIT_TNPIN_FALLING_EDGE                        (1 << 1) | (1 << 2)
#define TIMER16BIT_TNPIN_RISING_EDGE                         (1 << 0) | (1 << 1) | (1 << 2)

#define TIMER16BIT_FORCE_OUTPUT_COMPARE_A                    (1 << 7)
#define TIMER16BIT_FORCE_OUTPUT_COMPARE_B                    (1 << 6)
#define TIMER16BIT_FORCE_OUTPUT_COMPARE_C                    (1 << 5)

#define TIMER16BIT_INPUT_CAPTURE_INTERRUPT_ENABLE            (1 << 5)
#define TIMER16BIT_OUTPUT_COMPARE_C_MATCH_INTERRUPT_ENABLE   (1 << 3)
#define TIMER16BIT_OUTPUT_COMPARE_B_MATCH_INTERRUPT_ENABLE   (1 << 2)
#define TIMER16BIT_OUTPUT_COMPARE_A_MATCH_INTERRUPT_ENABLE   (1 << 1)
#define TIMER16BIT_OVERFLOW_INTERRUPT_ENABLE                 (1 << 0)

#define TIMER16BIT_INPUT_CAPTURE_FLAG                        (1 << 5)
#define TIMER16BIT_OUTPUT_COMPARE_C_MATCH_FLAG               (1 << 3)
#define TIMER16BIT_OUTPUT_COMPARE_B_MATCH_FLAG               (1 << 2)
#define TIMER16BIT_OUTPUT_COMPARE_A_MATCH_FLAG               (1 << 1)
#define TIMER16BIT_OVERFLOW_FLAG                             (1 << 0)